<?php

namespace wise\OwnerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BailRepository extends EntityRepository
{
}
