<?php

namespace wise\OwnerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BienRepository extends EntityRepository
{
}
