<?php

namespace wise\OwnerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LocataireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocataireRepository extends EntityRepository
{
}
