<?php

namespace wise\OwnerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * pictureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class pictureRepository extends EntityRepository
{
}
