wise_owner_message:
    resource: "@wiseOwnerBundle/Controller/MessageController.php"
    type:     annotation

wise_owner:
    resource: "@wiseOwnerBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_security_login:
    path: /login
    defaults:
        _controller: "wiseOwnerBundle:Default:login"

