wise_owner_annonce:
    resource: "@wiseOwnerBundle/Resources/config/routing/annonce.yml"
    prefix:   /annonce

wise_owner_bien:
    resource: "@wiseOwnerBundle/Resources/config/routing/bien.yml"
    prefix:   customer/bien

wise_owner_document:
    resource: "@wiseOwnerBundle/Resources/config/routing/document.yml"
    prefix:   /document

wise_owner_locataire:
    resource: "@wiseOwnerBundle/Resources/config/routing/locataire.yml"
    prefix:   /secured/locataire

wise_owner_proprietaire:
    resource: "@wiseOwnerBundle/Resources/config/routing/proprietaire.yml"
    prefix:   /secured/proprietaire

wise_owner_homepage:
    path:     /owner/
    defaults:
        _controller: wiseOwnerBundle:Default:index

wise_owner_customer_homepage:
    path:     /customer/
    defaults: { _controller: wiseOwnerBundle:Default:welcomeCustomer }

wise_user_registration:
    path:     /registration/
    defaults: { _controller: wiseOwnerBundle:Default:userResgistration }

owner_left_menu:
    path: /owner/menu
    defaults:
        _controller: wiseOwnerBundle:Proprietaire:generateLeftMenu
        _routes:
        # Les params pour cette route ne fonctionnent pas. Voir pourquoi.
          owner_welcome: wise_owner_homepage
          owner_biens: wise_owner_bien

wise_welcome:
    path:     /
    defaults:
        _controller: wiseOwnerBundle:Default:welcome
