services:
#    wise_owner.example:
#        class: wise\OwnerBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    wise.user_provider:
        class: wise\OwnerBundle\Provider\UserProvider
        arguments:
            userManager: "@doctrine.orm.entity_manager"
    wise.customer_provider:
        class: wise\OwnerBundle\Provider\CustomerProvider
        arguments:
            userManager: "@doctrine.orm.entity_manager"
