bien_index:
    path:     /
    defaults: { _controller: "wiseOwnerBundle:Bien:index" }
    methods:  GET

bien_show:
    path:     /{id}/show
    defaults: { _controller: "wiseOwnerBundle:Bien:show" }
    methods:  GET

bien_new:
    path:     /new
    defaults: { _controller: "wiseOwnerBundle:Bien:new" }
    methods:  [GET, POST]

bien_edit:
    path:     /{id}/edit
    defaults: { _controller: "wiseOwnerBundle:Bien:edit" }
    methods:  [GET, POST]

bien_delete:
    path:     /{id}/delete
    defaults: { _controller: "wiseOwnerBundle:Bien:delete" }
    methods:  DELETE
