document_index:
    path:     /
    defaults: { _controller: "wiseOwnerBundle:Document:index" }
    methods:  GET

document_show:
    path:     /{id}/show
    defaults: { _controller: "wiseOwnerBundle:Document:show" }
    methods:  GET

document_new:
    path:     /new
    defaults: { _controller: "wiseOwnerBundle:Document:new" }
    methods:  [GET, POST]

document_edit:
    path:     /{id}/edit
    defaults: { _controller: "wiseOwnerBundle:Document:edit" }
    methods:  [GET, POST]

document_delete:
    path:     /{id}/delete
    defaults: { _controller: "wiseOwnerBundle:Document:delete" }
    methods:  DELETE
